name: smittytester
favicon: null
layout_spectrum: 0.6437702504917979
typography_spectrum: 0.653827088419348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5027612871490419
  lightness: 0.8706006568390876
  saturation: 0.4350775759667158
  rhythmicContrast: 0.3472520166542381
purpose: []
